[2023-02-10 08:24:55,310] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:24:51.404515+00:00 [queued]>
[2023-02-10 08:24:55,337] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:24:51.404515+00:00 [queued]>
[2023-02-10 08:24:55,339] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 08:24:55,341] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-10 08:24:55,343] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 08:24:55,376] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-10 08:24:51.404515+00:00
[2023-02-10 08:24:55,385] {standard_task_runner.py:52} INFO - Started process 851 to run task
[2023-02-10 08:24:55,397] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-10T08:24:51.404515+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmpn6q9pesj', '--error-file', '/tmp/tmpfy8mp25v']
[2023-02-10 08:24:55,400] {standard_task_runner.py:77} INFO - Job 32: Subtask launching_chrome
[2023-02-10 08:24:55,533] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:24:51.404515+00:00 [running]> on host 0d4e6ddbf377
[2023-02-10 08:24:55,634] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T08:24:51.404515+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T08:24:51.404515+00:00
[2023-02-10 08:24:55,637] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-10 08:24:55,788] {logger.py:11} INFO - There is no [linux64] chromedriver for browser None in cache
[2023-02-10 08:24:55,791] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_linux64.zip
[2023-02-10 08:24:55,982] {logging_mixin.py:109} WARNING - [WDM] - Downloading:   0%|          | 0.00/6.96M [00:00<?, ?B/s]
[2023-02-10 08:24:56,085] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  19%|#9        | 1.34M/6.96M [00:00<00:00, 14.0MB/s]
[2023-02-10 08:24:56,185] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  66%|######5   | 4.59M/6.96M [00:00<00:00, 25.8MB/s]
[2023-02-10 08:24:56,227] {logging_mixin.py:109} WARNING - [WDM] - Downloading: 100%|##########| 6.96M/6.96M [00:00<00:00, 30.6MB/s]
[2023-02-10 08:24:56,228] {logging_mixin.py:109} WARNING - 
[2023-02-10 08:24:56,759] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/109.0.5414]
[2023-02-10 08:24:57,285] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 121, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(version="109.0.5414.74").install()))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/109.0.5414/chromedriver unexpectedly exited. Status code was: 127

[2023-02-10 08:24:57,336] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230210T082451, start_date=20230210T082455, end_date=20230210T082457
[2023-02-10 08:24:57,366] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 121, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(version="109.0.5414.74").install()))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/109.0.5414/chromedriver unexpectedly exited. Status code was: 127

[2023-02-10 08:24:57,399] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-10 08:24:57,459] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
