[2023-02-20 21:52:11,866] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:52:09.356859+00:00 [queued]>
[2023-02-20 21:52:11,884] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:52:09.356859+00:00 [queued]>
[2023-02-20 21:52:11,886] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:52:11,887] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-20 21:52:11,888] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 21:52:11,909] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-20 21:52:09.356859+00:00
[2023-02-20 21:52:11,917] {standard_task_runner.py:52} INFO - Started process 849 to run task
[2023-02-20 21:52:11,929] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-20T21:52:09.356859+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmpb7vi23rg', '--error-file', '/tmp/tmpyxutnf8y']
[2023-02-20 21:52:11,931] {standard_task_runner.py:77} INFO - Job 139: Subtask launching_chrome
[2023-02-20 21:52:12,076] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-20T21:52:09.356859+00:00 [running]> on host 1b319cb4c67b
[2023-02-20 21:52:12,232] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T21:52:09.356859+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T21:52:09.356859+00:00
[2023-02-20 21:52:12,238] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-20 21:52:12,489] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 110.0.5481
[2023-02-20 21:52:12,857] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
[2023-02-20 21:52:32,070] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 140, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x556e650a5d93 <unknown>
#1 0x556e64e742d7 <unknown>
#2 0x556e64eb0caa <unknown>
#3 0x556e64eb0db1 <unknown>
#4 0x556e64eee8f4 <unknown>
#5 0x556e64ed461d <unknown>
#6 0x556e64eec619 <unknown>
#7 0x556e64ed4353 <unknown>
#8 0x556e64ea3e40 <unknown>
#9 0x556e64ea5038 <unknown>
#10 0x556e650f98be <unknown>
#11 0x556e650fd8f0 <unknown>
#12 0x556e650ddf90 <unknown>
#13 0x556e650feb7d <unknown>
#14 0x556e650cf578 <unknown>
#15 0x556e65123348 <unknown>
#16 0x556e651234d6 <unknown>
#17 0x556e6513d341 <unknown>
#18 0x7fa1e0d44fa3 start_thread

[2023-02-20 21:52:32,103] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230220T215209, start_date=20230220T215211, end_date=20230220T215232
[2023-02-20 21:52:32,141] {standard_task_runner.py:92} ERROR - Failed to execute job 139 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 140, in launch_chrome
    h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[5]/div[1]/div/div/div[2]/article/div[1]/div[2]/div[1]/a/div/h3"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
#0 0x556e650a5d93 <unknown>
#1 0x556e64e742d7 <unknown>
#2 0x556e64eb0caa <unknown>
#3 0x556e64eb0db1 <unknown>
#4 0x556e64eee8f4 <unknown>
#5 0x556e64ed461d <unknown>
#6 0x556e64eec619 <unknown>
#7 0x556e64ed4353 <unknown>
#8 0x556e64ea3e40 <unknown>
#9 0x556e64ea5038 <unknown>
#10 0x556e650f98be <unknown>
#11 0x556e650fd8f0 <unknown>
#12 0x556e650ddf90 <unknown>
#13 0x556e650feb7d <unknown>
#14 0x556e650cf578 <unknown>
#15 0x556e65123348 <unknown>
#16 0x556e651234d6 <unknown>
#17 0x556e6513d341 <unknown>
#18 0x7fa1e0d44fa3 start_thread

[2023-02-20 21:52:32,195] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-20 21:52:32,252] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
