[2023-02-10 09:07:54,270] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T09:07:50.346126+00:00 [queued]>
[2023-02-10 09:07:54,300] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T09:07:50.346126+00:00 [queued]>
[2023-02-10 09:07:54,301] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 09:07:54,303] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-10 09:07:54,304] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 09:07:54,329] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-10 09:07:50.346126+00:00
[2023-02-10 09:07:54,342] {standard_task_runner.py:52} INFO - Started process 1358 to run task
[2023-02-10 09:07:54,359] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-10T09:07:50.346126+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmpfflc6xmd', '--error-file', '/tmp/tmpkwbg6t_8']
[2023-02-10 09:07:54,363] {standard_task_runner.py:77} INFO - Job 54: Subtask launching_chrome
[2023-02-10 09:07:54,570] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-10T09:07:50.346126+00:00 [running]> on host b700b67c38c5
[2023-02-10 09:07:54,748] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T09:07:50.346126+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T09:07:50.346126+00:00
[2023-02-10 09:07:54,752] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 121, in launch_chrome
    driver = webdriver.Chrome(path="/usr/local/bin/chromedriver")
TypeError: __init__() got an unexpected keyword argument 'path'
[2023-02-10 09:07:54,826] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230210T090750, start_date=20230210T090754, end_date=20230210T090754
[2023-02-10 09:07:54,881] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 121, in launch_chrome
    driver = webdriver.Chrome(path="/usr/local/bin/chromedriver")
TypeError: __init__() got an unexpected keyword argument 'path'
[2023-02-10 09:07:54,943] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-10 09:07:55,030] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
