[2023-02-10 08:04:44,375] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:04:40.427370+00:00 [queued]>
[2023-02-10 08:04:44,390] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:04:40.427370+00:00 [queued]>
[2023-02-10 08:04:44,391] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 08:04:44,392] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-10 08:04:44,394] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 08:04:44,415] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-10 08:04:40.427370+00:00
[2023-02-10 08:04:44,423] {standard_task_runner.py:52} INFO - Started process 117 to run task
[2023-02-10 08:04:44,428] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-10T08:04:40.427370+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmp9isnglsp', '--error-file', '/tmp/tmpm_dvc59v']
[2023-02-10 08:04:44,430] {standard_task_runner.py:77} INFO - Job 29: Subtask launching_chrome
[2023-02-10 08:04:44,565] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-10T08:04:40.427370+00:00 [running]> on host 0d4e6ddbf377
[2023-02-10 08:04:44,675] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T08:04:40.427370+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T08:04:40.427370+00:00
[2023-02-10 08:04:44,678] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-10 08:04:44,780] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome None
[2023-02-10 08:04:44,973] {logger.py:11} INFO - There is no [linux64] chromedriver for browser None in cache
[2023-02-10 08:04:44,976] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
[2023-02-10 08:04:45,069] {logging_mixin.py:109} WARNING - [WDM] - Downloading:   0%|          | 0.00/7.05M [00:00<?, ?B/s]
[2023-02-10 08:04:45,174] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  37%|###7      | 2.62M/7.05M [00:00<00:00, 26.9MB/s]
[2023-02-10 08:04:45,276] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  98%|#########7| 6.89M/7.05M [00:00<00:00, 36.9MB/s]
[2023-02-10 08:04:45,283] {logging_mixin.py:109} WARNING - [WDM] - Downloading: 100%|##########| 7.05M/7.05M [00:00<00:00, 35.1MB/s]
[2023-02-10 08:04:45,285] {logging_mixin.py:109} WARNING - 
[2023-02-10 08:04:45,581] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481]
[2023-02-10 08:04:46,098] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 120, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver unexpectedly exited. Status code was: 127

[2023-02-10 08:04:46,123] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230210T080440, start_date=20230210T080444, end_date=20230210T080446
[2023-02-10 08:04:46,144] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 120, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver unexpectedly exited. Status code was: 127

[2023-02-10 08:04:46,182] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-10 08:04:46,237] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
