[2023-02-20 20:49:58,145] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T20:49:55.641951+00:00 [queued]>
[2023-02-20 20:49:58,160] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.launching_chrome manual__2023-02-20T20:49:55.641951+00:00 [queued]>
[2023-02-20 20:49:58,162] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 20:49:58,163] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-02-20 20:49:58,163] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-02-20 20:49:58,191] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): launching_chrome> on 2023-02-20 20:49:55.641951+00:00
[2023-02-20 20:49:58,204] {standard_task_runner.py:52} INFO - Started process 201 to run task
[2023-02-20 20:49:58,211] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'launching_chrome', 'manual__2023-02-20T20:49:55.641951+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/reddit_ingestion_dag.py', '--cfg-path', '/tmp/tmp9_7dl8uv', '--error-file', '/tmp/tmpibw2ytgu']
[2023-02-20 20:49:58,216] {standard_task_runner.py:77} INFO - Job 106: Subtask launching_chrome
[2023-02-20 20:49:58,331] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.launching_chrome manual__2023-02-20T20:49:55.641951+00:00 [running]> on host de4414e9a637
[2023-02-20 20:49:58,415] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=launching_chrome
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T20:49:55.641951+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T20:49:55.641951+00:00
[2023-02-20 20:49:58,418] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-20 20:49:58,533] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome None
[2023-02-20 20:49:59,145] {logger.py:11} INFO - There is no [linux64] chromedriver for browser None in cache
[2023-02-20 20:49:59,146] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
[2023-02-20 20:49:59,303] {logging_mixin.py:109} WARNING - [WDM] - Downloading:   0%|          | 0.00/7.05M [00:00<?, ?B/s]
[2023-02-20 20:49:59,406] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  14%|#4        | 1.00M/7.05M [00:00<00:00, 10.4MB/s]
[2023-02-20 20:49:59,506] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  51%|#####     | 3.59M/7.05M [00:00<00:00, 20.2MB/s]
[2023-02-20 20:49:59,628] {logging_mixin.py:109} WARNING - [WDM] - Downloading:  92%|#########2| 6.49M/7.05M [00:00<00:00, 22.6MB/s]
[2023-02-20 20:49:59,660] {logging_mixin.py:109} WARNING - [WDM] - Downloading: 100%|##########| 7.05M/7.05M [00:00<00:00, 20.9MB/s]
[2023-02-20 20:49:59,661] {logging_mixin.py:109} WARNING - 
[2023-02-20 20:50:00,033] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481]
[2023-02-20 20:50:00,555] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 136, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver unexpectedly exited. Status code was: 127

[2023-02-20 20:50:00,585] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=launching_chrome, execution_date=20230220T204955, start_date=20230220T204958, end_date=20230220T205000
[2023-02-20 20:50:00,622] {standard_task_runner.py:92} ERROR - Failed to execute job 106 for task launching_chrome
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_ingestion_dag.py", line 136, in launch_chrome
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
    keep_alive,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver unexpectedly exited. Status code was: 127

[2023-02-20 20:50:00,664] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-20 20:50:00,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
